### PR TITLE
Some proofreading and refactoring

### PR DESCRIPTION
**Pull request by juleskers**
Hi Stephan!

Thank you for sharing the repo for this tool after our email discussions. I've had a look at it, and like what I see!

I've been doing 'active reading' while going through it, and wanted to polish the Readme a bit.
Here are the first few thing's I've changed in my local copy.

  - Polish Readme, so that it is easier to comprehend for people who haven't read our private email conversation :-)
  - Extracted the repeated `plot.bat` writing into a helper function
  - moved the `IGV_jar` path up in the file, so that it is more obvious it needs changing.

I'm still looking at compatibility with newer IGV versions.
Starting with IGV 2.5, Broad moved to Java Jigsaw-like modules, so there is no literal `igv.jar` anymore for us to call.
It should be fairly trivial to instead call `igv.sh` (which also passes through arguments), but I need to get the rest working first.

### CODE REVIEW

**Comment by juleskers** [comment]
Hi @StephanHolgerD ,

I'm calling it a day for now, but had great fun fiddling with this.

Can you please try my changes locally?
During testing I ran into some issues which I _think_ are local configuration problems, but one can never be too sure.

  - Don't have a working docker/singularity setup on this PC, so could only test locally
  - Don't have java8 installed, so can't use IGV 2.4 versions that come with a `igv.jar`
    - I hacked my local copy to call `igv.sh` instead, and this seems to _mostly_ work
  - With a relative directory `Snapshots` IGV 2.8.12 would crash with a nullpointer exception in `create_parents` when creating the snapshot dir.
    - but hardcoding the snapshot dir to `/home/my-user/snapshots` worked.
  - my local IGV hangs after the 4th snapshot, totally unresponsive; it needs a Ctrl+C to get out (and abort the script)


  - the `IGVLocal` variant specifies `--server-num=1`, but this opens IGV on my 'real' monitor. Wouldn't it make more sense to specify a higher server-num, so that it uses a virtual display?

**Comment by StephanHolgerD** [comment]
Hey @juleskers , thanks for contributing. 

* actually I never tested the local version, I check if i can reproduce your error
* I am not sure what changing the ```--server-num=1``` argument will cause, still a little inexperienced in using xfvb run , will check

**Comment by juleskers** [comment]
"server number" is X jargon.
Basically, any one computer can have multiple running X-servers (e.g. old mainframes with multiple terminals)
On modern systems, there is _usually_ only one X-server, although some more-obscure forms of multi-monitor setups have one server per monitor.

The primary X-server is usually "server 1", so telling XVFB to use that means it will share with the 'real' X-server.
It seems it would be better to omit it, as [the default is 99](https://helpmanual.io/man1/xvfb-run/) (i.e. "start really far away from real displays")

**Comment by StephanHolgerD** [comment]
sounds logical, so lets try this. 

Hope  i can start a test run this evening, I still got some other stuff to do :/

**Pull request merged**
